version: "3.9"
    
services:
  db:
    container_name: db
    image: mariadb:latest
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: symfony
      MARIADB_DATABASE: symfony_test
    networks:
      - db
    ports:
      - "4306:3306"
  
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    container_name: phpmyadmin
    networks:
      - db
    environment:
      PMA_HOST: db
    ports:
      - "9090:80"
    depends_on:
      - db
     
  symfony:
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ../symfony:/var/www/html:rw
    ports:
      - "8080:80"
    networks:
      - db 
      - symfony
    depends_on:
      - db

networks:
  db:
    driver: bridge
  symfony:
    driver: bridge

# volumes:
#   db_data: {}
#   symfony: {}










