version: "3.9"
    
services:
  db:
    image: mariadb:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: symfony
      MARIADB_DATABASE: symfony_test
      MARIADB_USER: symfony
      MARIADB_PASSWORD: symfony
  
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "3026:80"
    environment:
      MARIADB_ROOT_PASSWORD: symfony
      MARIADB_USER: symfony
      MARIADB_PASSWORD: symfony
      

  symfony:
    depends_on:
      - db
    #image: wordpress:latest
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ../symfony:/var/www/html
    ports:
      - "8080:80"
    expose:
      - 9000
      - 8080
    restart: unless-stopped 
volumes:
  db_data: {}
  symfony: {}









